// backpack_quant_trading/frontend/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login-bg"></div>
    <div class="login-card">
      <div class="login-brand">
        <div class="brand-icon">◈</div>
        <h1>沐龙量化</h1>
        <p>Quantitative Trading Platform</p>
      </div>
      <el-tabs v-model="activeTab" class="login-tabs">
        <el-tab-pane label="登录" name="login">
          <el-form :model="form" label-width="0" @submit.prevent="handleLogin">
            <el-form-item>
              <el-input v-model="form.username" placeholder="用户名" size="large" />
            </el-form-item>
            <el-form-item>
              <el-input v-model="form.password" type="password" placeholder="密码" size="large" show-password @keyup.enter="handleLogin" />
            </el-form-item>
            <el-form-item>
              <el-button type="primary" size="large" style="width: 100%" :loading="loading" @click="handleLogin">登录</el-button>
            </el-form-item>
          </el-form>
        </el-tab-pane>
        <el-tab-pane label="注册" name="register">
          <el-form :model="form" label-width="0" @submit.prevent="handleRegister">
            <el-form-item>
              <el-input v-model="form.username" placeholder="用户名" size="large" />
            </el-form-item>
            <el-form-item>
              <el-input v-model="form.password" type="password" placeholder="密码" size="large" show-password />
            </el-form-item>
            <el-form-item>
              <el-button type="success" size="large" style="width: 100%" :loading="loading" @click="handleRegister">注册</el-button>
            </el-form-item>
          </el-form>
        </el-tab-pane>
      </el-tabs>
      <el-alert v-if="message" :title="message" :type="messageType" show-icon style="margin-top: 12px" />
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { login, register } from '../api/auth'
import { useUserStore } from '../stores/user'

const router = useRouter()
const userStore = useUserStore()
const activeTab = ref('login')
const loading = ref(false)
const message = ref('')
const messageType = ref('success')
const form = reactive({ username: '', password: '' })

async function handleLogin() {
  if (!form.username || !form.password) {
    ElMessage.warning('请输入用户名和密码')
    return
  }
  loading.value = true
  message.value = ''
  try {
    const res = await login(form)
    userStore.setAuth(res.access_token, res.user)
    ElMessage.success('登录成功')
    router.push('/')
  } catch (e) {
    message.value = e.response?.data?.detail || '登录失败'
    messageType.value = 'error'
  } finally {
    loading.value = false
  }
}

async function handleRegister() {
  if (!form.username || !form.password) {
    ElMessage.warning('请输入用户名和密码')
    return
  }
  loading.value = true
  message.value = ''
  try {
    const res = await register(form)
    userStore.setAuth(res.access_token, res.user)
    ElMessage.success('注册成功')
    router.push('/')
  } catch (e) {
    message.value = e.response?.data?.detail || '注册失败'
    messageType.value = 'error'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  background: linear-gradient(165deg, #f4f6f9 0%, #e8eef4 50%, #dbeafe 100%);
}
.login-bg {
  position: absolute;
  inset: 0;
  background-image:
    radial-gradient(circle at 20% 30%, rgba(13, 148, 136, 0.06) 0%, transparent 50%),
    radial-gradient(circle at 80% 70%, rgba(8, 145, 178, 0.06) 0%, transparent 50%),
    linear-gradient(180deg, transparent 0%, rgba(255,255,255,0.8) 100%);
  pointer-events: none;
}
.login-card {
  width: 420px;
  padding: 48px 44px;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 16px;
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(255,255,255,0.8);
  position: relative;
  backdrop-filter: blur(12px);
}
.login-brand {
  text-align: center;
  margin-bottom: 32px;
}
.brand-icon {
  font-size: 32px;
  color: var(--color-primary);
  margin-bottom: 12px;
  letter-spacing: 2px;
}
.login-brand h1 {
  font-size: 22px;
  font-weight: 700;
  color: #1a2332;
  margin: 0 0 4px 0;
  letter-spacing: -0.02em;
}
.login-brand p {
  font-size: 13px;
  color: #8b99a8;
  margin: 0;
}
.login-tabs :deep(.el-tabs__header) { margin-bottom: 24px; }
.login-tabs :deep(.el-tabs__nav-wrap::after) { display: none; }
.login-tabs :deep(.el-tabs__item) { font-weight: 600; }
.login-tabs :deep(.el-tabs__indicator) { height: 3px; border-radius: 2px; }
.login-tabs :deep(.el-form-item) { margin-bottom: 20px; }
.login-tabs :deep(.el-input__wrapper) { padding: 12px 16px; border-radius: 10px; }
.login-tabs :deep(.el-button--primary) { height: 48px; font-weight: 600; border-radius: 10px; }
.login-tabs :deep(.el-button--success) { height: 48px; font-weight: 600; border-radius: 10px; }
</style>

// backpack_quant_trading/frontend/src/views/Login.jsx
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { login, register } from '../api/auth'
import './Login.css'

const Login = () => {
  const navigate = useNavigate()
  const [activeTab, setActiveTab] = useState('login')
  const [loading, setLoading] = useState(false)
  const [message, setMessage] = useState('')
  const [messageType, setMessageType] = useState('success')
  const [form, setForm] = useState({
    username: '',
    password: '',
    email: '',
    confirmPassword: '',
    remember: false,
  })

  const handleChange = (e) => {
    const { name, type, checked, value } = e.target
    setForm((prev) => ({ ...prev, [name]: type === 'checkbox' ? checked : value }))
  }

  const handleLogin = async () => {
    if (!form.username || !form.password) {
      setMessage('请输入用户名和密码')
      setMessageType('error')
      return
    }
    setLoading(true)
    setMessage('')
    try {
      const res = await login(form)
      localStorage.setItem('token', res.access_token)
      localStorage.setItem('user', JSON.stringify(res.user))
      setMessage('登录成功')
      setMessageType('success')
      navigate('/')
    } catch (e) {
      setMessage(e?.response?.data?.detail || '登录失败')
      setMessageType('error')
    } finally {
      setLoading(false)
    }
  }

  const handleRegister = async () => {
    if (!form.username || !form.password) {
      setMessage('请输入用户名和密码')
      setMessageType('error')
      return
    }
    setLoading(true)
    setMessage('')
    try {
      const res = await register(form)
      localStorage.setItem('token', res.access_token)
      localStorage.setItem('user', JSON.stringify(res.user))
      setMessage('注册成功')
      setMessageType('success')
      navigate('/')
    } catch (e) {
      setMessage(e?.response?.data?.detail || '注册失败')
      setMessageType('error')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="login-page">
      <div className="login-bg"></div>
      <div className="login-card">
        <div className="login-brand">
          <div className="brand-logo-box">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" className="brand-logo-icon">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
            </svg>
          </div>
          <h1>沐龙量化</h1>
          <p>Quantitative Trading Platform</p>
        </div>

        <div className="login-tabs">
          <div className="tabs-header">
            <button
              type="button"
              className={`tab-item${activeTab === 'login' ? ' active' : ''}`}
              onClick={() => setActiveTab('login')}
            >
              登录
            </button>
            <button
              type="button"
              className={`tab-item${activeTab === 'register' ? ' active' : ''}`}
              onClick={() => setActiveTab('register')}
            >
              注册
            </button>
          </div>

          <div className="tab-body">
            {activeTab === 'login' && (
              <>
                <div className="form-item">
                  <input
                    name="username"
                    value={form.username}
                    onChange={handleChange}
                    placeholder="用户名"
                    disabled={loading}
                  />
                </div>
                <div className="form-item">
                  <input
                    name="password"
                    type="password"
                    value={form.password}
                    onChange={handleChange}
                    placeholder="密码"
                    disabled={loading}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        handleLogin()
                      }
                    }}
                  />
                </div>
                <div className="login-extra-row">
                  <label className="checkbox-label">
                    <input
                      type="checkbox"
                      name="remember"
                      checked={form.remember}
                      onChange={handleChange}
                      disabled={loading}
                    />
                    记住我
                  </label>
                  <button type="button" className="link-inline" disabled>
                    忘记密码?
                  </button>
                </div>
                <div className="form-item">
                  <button
                    type="button"
                    className="btn btn-primary"
                    disabled={loading}
                    onClick={handleLogin}
                  >
                    {loading ? '处理中...' : '登录'}
                  </button>
                </div>
              </>
            )}

            {activeTab === 'register' && (
              <>
                <div className="form-item">
                  <input
                    name="username"
                    value={form.username}
                    onChange={handleChange}
                    placeholder="用户名"
                    disabled={loading}
                  />
                </div>
                <div className="form-item">
                  <input
                    name="email"
                    value={form.email}
                    onChange={handleChange}
                    placeholder="邮箱（可选）"
                    disabled={loading}
                  />
                </div>
                <div className="form-item">
                  <input
                    name="password"
                    type="password"
                    value={form.password}
                    onChange={handleChange}
                    placeholder="密码"
                    disabled={loading}
                  />
                </div>
                <div className="form-item">
                  <input
                    name="confirmPassword"
                    type="password"
                    value={form.confirmPassword}
                    onChange={handleChange}
                    placeholder="确认密码"
                    disabled={loading}
                  />
                </div>
                <div className="terms-row">
                  <label className="checkbox-label">
                    <input
                      type="checkbox"
                      name="agree"
                      onChange={() => {}}
                    />
                    <span>
                      我同意
                      <button type="button" className="link-inline" disabled>
                        服务条款
                      </button>
                      和
                      <button type="button" className="link-inline" disabled>
                        隐私政策
                      </button>
                    </span>
                  </label>
                </div>
                <div className="form-item">
                  <button
                    type="button"
                    className="btn btn-success"
                    disabled={loading}
                    onClick={handleRegister}
                  >
                    {loading ? '处理中...' : '注册'}
                  </button>
                </div>
              </>
            )}
          </div>
        </div>

        {message && (
          <div className={`login-alert ${messageType === 'error' ? 'login-alert-error' : 'login-alert-success'}`}>
            {message}
          </div>
        )}

        <div className="login-footer">
          © 2024 沐龙量化. All rights reserved.
        </div>
      </div>
    </div>
  )
}

export default Login
