// backpack_quant_trading/frontend/src/views/AiLab.vue
<template>
  <div class="page ai-lab-page">
    <div class="title-row">
      <h2>AI 自适应实验室</h2>
    </div>

    <el-card class="input-card">
      <h4>输入数据</h4>
      <el-form label-width="0">
        <el-form-item>
          <span class="label">1. 上传 K 线截图</span>
          <el-upload
            class="upload-area"
            :auto-upload="false"
            :show-file-list="false"
            :on-change="onFileChange"
          >
            <div class="upload-inner">拖拽或 选择图片</div>
          </el-upload>
          <div v-if="imagePreview" class="preview">
            <img :src="imagePreview" alt="preview" />
          </div>
        </el-form-item>
        <el-form-item>
          <span class="label">2. 选择币种与K线周期</span>
          <div class="symbol-interval-row">
            <el-select
              v-model="selectedSymbol"
              filterable
              clearable
              placeholder="选择币安合约交易对，如 ETHUSDT"
              class="symbol-select"
              :filter-method="handleSymbolFilter"
              @visible-change="loadSymbols"
            >
              <el-option v-for="s in filteredSymbols" :key="s" :label="s" :value="s" />
            </el-select>
            <el-select v-model="interval" class="interval-select">
              <el-option v-for="opt in intervalOptions" :key="opt.value" :label="opt.label" :value="opt.value" />
            </el-select>
          </div>
        </el-form-item>
        <el-form-item>
          <span class="label">3. 原始 OHLC 数据 (JSON)</span>
          <el-button type="warning" @click="fetchKline" :loading="fetching" class="fetch-btn">
            抓取最新行情
          </el-button>
          <el-input v-model="klineJson" type="textarea" :rows="6" placeholder='[{"time": 123, "open": 100, "high": 101, "low": 99, "close": 100}]' class="kline-textarea" />
        </el-form-item>
        <el-form-item>
          <span class="label">4. 分析指令 (驯化提示词)</span>
          <el-input v-model="userQuery" placeholder="请根据当前的 K 线图形和原始数据，识别趋势并标注买卖点。" class="query-input" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="runAnalyze" :loading="analyzing" class="analyze-btn">
            开始 AI 综合分析
          </el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <el-card class="chart-card">
      <h4>K 线策略可视化</h4>
      <div ref="chartRef" class="chart-container"></div>
    </el-card>

    <el-card class="output-card">
      <h4>DeepSeek V3 策略分析报告</h4>
      <div class="output-content">{{ analysisOutput || '等待分析...' }}</div>
    </el-card>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import * as echarts from 'echarts'
import { ElMessage } from 'element-plus'
import { fetchKline as apiFetchKline, runAnalyze as apiRunAnalyze } from '../api/aiLab'
import { getSymbols } from '../api/currencyMonitor'

const chartRef = ref(null)
const imagePreview = ref('')
const imageBase64 = ref('')
const klineJson = ref('')
const userQuery = ref('请根据当前的 K 线图形和原始数据，识别趋势并标注买卖点。')
const analysisOutput = ref('')
const suggestedBuy = ref([])
const suggestedSell = ref([])
const fetching = ref(false)
const analyzing = ref(false)

// 币种与周期选择
const symbolList = ref([])
const filteredSymbols = ref([])
const selectedSymbol = ref('ETHUSDT')
const interval = ref('15m')
const intervalOptions = [
  { label: '1分钟', value: '1m' },
  { label: '15分钟', value: '15m' },
  { label: '1小时', value: '1h' },
  { label: '2小时', value: '2h' },
  { label: '4小时', value: '4h' },
  { label: '日线', value: '1d' },
  { label: '周线', value: '1w' },
]

function onFileChange(file) {
  const reader = new FileReader()
  reader.onload = (e) => {
    imagePreview.value = e.target.result
    imageBase64.value = e.target.result
  }
  reader.readAsDataURL(file.raw)
}

async function loadSymbols(visible) {
  if (!visible) return
  if (symbolList.value.length) {
    filteredSymbols.value = symbolList.value
    return
  }
  try {
    const res = await getSymbols()
    const list = Array.isArray(res.symbols) ? res.symbols : []
    symbolList.value = list
    filteredSymbols.value = list
  } catch (e) {
    ElMessage.error('获取币安合约列表失败')
  }
}

function handleSymbolFilter(query) {
  const kw = (query || '').toUpperCase()
  if (!kw) {
    filteredSymbols.value = symbolList.value
  } else {
    filteredSymbols.value = symbolList.value.filter((s) => s.includes(kw))
  }
}

async function fetchKline() {
  fetching.value = true
  try {
    if (!selectedSymbol.value) {
      ElMessage.warning('请先选择币种')
      fetching.value = false
      return
    }
    const res = await apiFetchKline({ symbol: selectedSymbol.value, interval: interval.value, limit: 1500 })
    if (res.error) {
      ElMessage.error(res.error)
    } else if (res.data) {
      klineJson.value = JSON.stringify(res.data, null, 2)
      ElMessage.success('抓取成功')
    }
  } catch (e) {
    ElMessage.error('抓取失败')
  } finally {
    fetching.value = false
  }
}

async function runAnalyze() {
  analyzing.value = true
  analysisOutput.value = ''
  try {
    let kj = null
    if (klineJson.value) {
      try {
        kj = JSON.parse(klineJson.value)
      } catch {
        kj = klineJson.value
      }
    }
    const res = await apiRunAnalyze({
      image_base64: imageBase64.value || undefined,
      kline_json: kj,
      user_query: userQuery.value,
      symbol: selectedSymbol.value || 'ETHUSDT',
      interval: interval.value || '15m',
    })
    analysisOutput.value = res.analysis || ''
    suggestedBuy.value = res.buy || []
    suggestedSell.value = res.sell || []
    ElMessage.success('分析完成')
  } catch (e) {
    ElMessage.error(e.response?.data?.detail || '分析失败')
  } finally {
    analyzing.value = false
  }
}

function renderChart() {
  if (!chartRef.value || !klineJson.value) return
  let data
  try {
    data = JSON.parse(klineJson.value)
  } catch {
    return
  }
  if (Array.isArray(data) && data.length === 0) return
  if (data?.data) data = data.data
  const times = data.map((d) => {
    const t = d.time
    const ms = t < 10000000000 ? t * 1000 : t
    return new Date(ms).toLocaleString()
  })
  const o = data.map((d) => d.open)
  const h = data.map((d) => d.high)
  const l = data.map((d) => d.low)
  const c = data.map((d) => d.close)
  const candlestickData = data.map((d, i) => [o[i], c[i], l[i], h[i]])

  // 每屏约 200 根 K 线，保证每根有足够宽度可读
  const maxVisible = 200
  const total = data.length
  let zoomStart = 0
  let zoomEnd = 100
  if (total > maxVisible) {
    zoomStart = ((total - maxVisible) / total) * 100
    zoomEnd = 100
  }

  const ch = echarts.init(chartRef.value)

  // 构建买卖点标注：为每个建议价位找到最接近的 K 线位置
  const markPoints = []
  const buys = [...new Set(suggestedBuy.value)].map(Number).filter((p) => p > 0)
  const sells = [...new Set(suggestedSell.value)].map(Number).filter((p) => p > 0)
  const allPrices = buys.map((p) => ({ p, type: '买' })).concat(sells.map((p) => ({ p, type: '卖' })))
  for (const { p, type } of allPrices) {
    let bestIdx = 0
    let bestDist = Infinity
    for (let i = 0; i < data.length; i++) {
      const close = Number(data[i].close)
      const dist = Math.abs(close - p)
      if (dist < bestDist) {
        bestDist = dist
        bestIdx = i
      }
    }
    markPoints.push({
      name: type,
      coord: [bestIdx, p],
      value: p.toFixed(2),
      itemStyle: { color: type === '买' ? '#10b981' : '#ef4444' },
    })
  }

  const option = {
    xAxis: { type: 'category', data: times, boundaryGap: true },
    yAxis: {
      type: 'value',
      scale: true, // 根据数据自动缩放，不再从 0 开始，避免大量空白
      splitLine: { lineStyle: { type: 'dashed', opacity: 0.3 } },
    },
    dataZoom: [
      { type: 'inside', xAxisIndex: 0, start: zoomStart, end: zoomEnd },
      { type: 'slider', xAxisIndex: 0, start: zoomStart, end: zoomEnd, height: 24 },
    ],
    series: [
      {
        type: 'candlestick',
        data: candlestickData,
        itemStyle: { color: '#ef4444', color0: '#10b981', borderColor: '#ef4444', borderColor0: '#10b981', borderWidth: 1.5 },
        markPoint: markPoints.length
          ? { data: markPoints, symbol: 'pin', symbolSize: 40, label: { fontSize: 12 } }
          : undefined,
      },
    ],
    grid: { left: 60, right: 30, top: 30, bottom: 90 },
  }
  ch.setOption(option)
}

watch([klineJson, suggestedBuy, suggestedSell], () => renderChart(), { immediate: true })
</script>

<style scoped>
.title-row {
  display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 24px; padding-left: 16px; border-left: 4px solid var(--color-primary);
}
.title-row h2 { margin: 0; font-size: 22px; font-weight: 700; color: var(--color-text); }
.input-card {
  max-width: none;
  margin: 0 0 24px 0;
  padding: 24px 28px;
  background: var(--color-bg-card);
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border);
}
.input-card h4 { color: var(--color-primary); margin-bottom: 20px; text-align: center; font-weight: 600; font-size: 16px; }
.input-card .el-form-item { margin-bottom: 20px; }
.label { display: block; margin-bottom: 8px; font-weight: 600; font-size: 14px; color: var(--color-text); }
.upload-area { width: 100%; }
.upload-inner {
  width: 100%;
  height: 80px;
  line-height: 80px;
  font-size: 14px;
  color: var(--color-text-muted);
  border: 2px dashed var(--color-border);
  border-radius: 10px;
  text-align: center;
  background: #fafbfc;
  cursor: pointer;
  transition: border-color 0.2s, background 0.2s, color 0.2s;
}
.upload-inner:hover { border-color: var(--color-primary); background: rgba(245, 158, 11, 0.04); color: var(--color-text); }
.fetch-btn { width: 100%; height: 40px; font-size: 14px; font-weight: 600; margin-bottom: 10px; }
.symbol-interval-row {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 4px;
}
.symbol-select { min-width: 220px; max-width: 320px; }
.interval-select { width: 140px; }
.kline-textarea :deep(.el-textarea__inner) {
  min-height: 120px !important;
  font-size: 13px;
  padding: 12px 14px;
  font-family: var(--font-mono);
  background: #1e293b;
  color: #e2e8f0;
  border: 1px solid #334155;
  border-radius: 10px;
  resize: vertical;
}
.kline-textarea :deep(.el-textarea__inner::placeholder) { color: #94a3b8; }
.kline-textarea :deep(.el-textarea__inner:focus) {
  border-color: var(--color-primary);
  box-shadow: 0 0 0 2px rgba(245, 158, 11, 0.2);
}
.query-input :deep(.el-input__wrapper) { min-height: 40px; padding: 10px 14px; }
.analyze-btn { width: 100%; height: 44px; font-size: 15px; font-weight: 600; }
.preview { margin-top: 12px; text-align: center; }
.preview img { max-width: 100%; max-height: 200px; border-radius: var(--radius-md); }
.chart-card { margin-bottom: 24px; padding: 24px; }
.chart-card h4 { color: var(--color-primary); margin-bottom: 20px; text-align: center; font-weight: 600; font-size: 16px; }
.chart-container { height: 420px; min-height: 360px; }
.output-card { padding: 24px; }
.output-card h4 { color: var(--color-primary); margin-bottom: 20px; text-align: center; font-weight: 600; font-size: 16px; }
.output-content {
  white-space: pre-wrap;
  font-size: 14px;
  line-height: 2;
  max-height: 320px;
  overflow-y: auto;
  padding: 20px;
  background: #f8fafc;
  border-radius: var(--radius-md);
  border: 1px solid var(--color-border);
  font-family: var(--font-mono);
}
</style>

// backpack_quant_trading/frontend/src_ai/imports/pasted_text/ai-lab.tsx
import React, { useEffect, useRef, useState } from 'react'
import * as echarts from 'echarts'
import { fetchKline as apiFetchKline, runAnalyze as apiRunAnalyze } from '../api/aiLab'
import { getSymbols } from '../api/currencyMonitor'
import './AiLab.css'

const INTERVAL_OPTIONS = [
  { label: '1分钟', value: '1m' },
  { label: '15分钟', value: '15m' },
  { label: '1小时', value: '1h' },
  { label: '2小时', value: '2h' },
  { label: '4小时', value: '4h' },
  { label: '日线', value: '1d' },
  { label: '周线', value: '1w' },
]

const AiLab = () => {
  const chartRef = useRef(null)
  const [imagePreview, setImagePreview] = useState('')
  const [imageBase64, setImageBase64] = useState('')
  const [klineJson, setKlineJson] = useState('')
  const [userQuery, setUserQuery] = useState(
    '请根据当前的 K 线图形和原始数据，识别趋势并标注买卖点。'
  )
  const [analysisOutput, setAnalysisOutput] = useState('')
  const [suggestedBuy, setSuggestedBuy] = useState([])
  const [suggestedSell, setSuggestedSell] = useState([])
  const [fetching, setFetching] = useState(false)
  const [analyzing, setAnalyzing] = useState(false)
  const [symbolList, setSymbolList] = useState([])
  const [filteredSymbols, setFilteredSymbols] = useState([])
  const [selectedSymbol, setSelectedSymbol] = useState('ETHUSDT')
  const [interval, setInterval] = useState('15m')
  const [symbolKeyword, setSymbolKeyword] = useState('')

  const onFileChange = (e) => {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = (ev) => {
      setImagePreview(ev.target.result)
      setImageBase64(ev.target.result)
    }
    reader.readAsDataURL(file)
  }

  const loadSymbols = async () => {
    if (symbolList.length) {
      setFilteredSymbols(symbolList)
      return
    }
    try {
      const res = await getSymbols()
      const list = Array.isArray(res.symbols) ? res.symbols : []
      setSymbolList(list)
      setFilteredSymbols(list)
    } catch (_) {
      alert('获取币安合约列表失败')
    }
  }

  const handleSymbolFilter = (e) => {
    const kw = (e.target.value || '').toUpperCase()
    if (!kw) setFilteredSymbols(symbolList)
    else setFilteredSymbols(symbolList.filter((s) => s.includes(kw)))
  }

  const fetchKline = async () => {
    if (!selectedSymbol) {
      alert('请先选择币种')
      return
    }
    setFetching(true)
    try {
      const res = await apiFetchKline({
        symbol: selectedSymbol,
        interval,
        limit: 1500,
      })
      if (res.error) alert(res.error)
      else if (res.data) {
        setKlineJson(JSON.stringify(res.data, null, 2))
        alert('抓取成功')
      }
    } catch (_) {
      alert('抓取失败')
    } finally {
      setFetching(false)
    }
  }

  const runAnalyze = async () => {
    setAnalyzing(true)
    setAnalysisOutput('')
    try {
      let kj = null
      if (klineJson) {
        try {
          kj = JSON.parse(klineJson)
        } catch {
          kj = klineJson
        }
      }
      const res = await apiRunAnalyze({
        image_base64: imageBase64 || undefined,
        kline_json: kj,
        user_query: userQuery,
        symbol: selectedSymbol || 'ETHUSDT',
        interval: interval || '15m',
      })
      setAnalysisOutput(res.analysis || '')
      setSuggestedBuy(res.buy || [])
      setSuggestedSell(res.sell || [])
      alert('分析完成')
    } catch (e) {
      alert(e?.response?.data?.detail || '分析失败')
    } finally {
      setAnalyzing(false)
    }
  }

  const renderChart = () => {
    if (!chartRef.current || !klineJson) return
    let data
    try {
      data = JSON.parse(klineJson)
    } catch {
      return
    }
    if (Array.isArray(data) && data.length === 0) return
    if (data?.data) data = data.data
    const times = data.map((d) => {
      const t = d.time
      const ms = t < 10000000000 ? t * 1000 : t
      return new Date(ms).toLocaleString()
    })
    const o = data.map((d) => d.open)
    const c = data.map((d) => d.close)
    const l = data.map((d) => d.low)
    const h = data.map((d) => d.high)
    const candlestickData = data.map((d, i) => [o[i], c[i], l[i], h[i]])
    const maxVisible = 200
    const total = data.length
    let zoomStart = 0
    let zoomEnd = 100
    if (total > maxVisible) {
      zoomStart = ((total - maxVisible) / total) * 100
    }
    const markPoints = []
    const buys = [...new Set(suggestedBuy)].map(Number).filter((p) => p > 0)
    const sells = [...new Set(suggestedSell)].map(Number).filter((p) => p > 0)
    const allPrices = [
      ...buys.map((p) => ({ p, type: '买' })),
      ...sells.map((p) => ({ p, type: '卖' })),
    ]
    for (const { p, type } of allPrices) {
      let bestIdx = 0
      let bestDist = Infinity
      for (let i = 0; i < data.length; i++) {
        const dist = Math.abs(Number(data[i].close) - p)
        if (dist < bestDist) {
          bestDist = dist
          bestIdx = i
        }
      }
      markPoints.push({
        name: type,
        coord: [bestIdx, p],
        value: p.toFixed(2),
        itemStyle: { color: type === '买' ? '#10b981' : '#ef4444' },
      })
    }
    const ch = echarts.init(chartRef.current)
    ch.setOption({
      xAxis: { type: 'category', data: times, boundaryGap: true },
      yAxis: {
        type: 'value',
        scale: true,
        splitLine: { lineStyle: { type: 'dashed', opacity: 0.3 } },
      },
      dataZoom: [
        { type: 'inside', xAxisIndex: 0, start: zoomStart, end: zoomEnd },
        { type: 'slider', xAxisIndex: 0, start: zoomStart, end: zoomEnd, height: 24 },
      ],
      series: [
        {
          type: 'candlestick',
          data: candlestickData,
          itemStyle: {
            color: '#ef4444',
            color0: '#10b981',
            borderColor: '#ef4444',
            borderColor0: '#10b981',
            borderWidth: 1.5,
          },
          markPoint:
            markPoints.length
              ? { data: markPoints, symbol: 'pin', symbolSize: 40, label: { fontSize: 12 } }
              : undefined,
        },
      ],
      grid: { left: 60, right: 30, top: 30, bottom: 90 },
    })
  }

  useEffect(() => {
    renderChart()
  }, [klineJson, suggestedBuy, suggestedSell])

  return (
    <div className="page ai-lab-page">
      <div className="title-row">
        <h2>AI 自适应实验室</h2>
      </div>

      <div className="input-card card-block">
        <h4>输入数据</h4>
        <div className="form-item">
          <span className="label">1. 上传 K 线截图</span>
          <label className="upload-area">
            <input type="file" accept="image/*" onChange={onFileChange} className="upload-input" />
            <div className="upload-inner">拖拽或 选择图片</div>
          </label>
          {imagePreview && (
            <div className="preview">
              <img src={imagePreview} alt="preview" />
            </div>
          )}
        </div>
        <div className="form-item">
          <span className="label">2. 选择币种与K线周期</span>
          <div className="symbol-interval-row">
            <input
              list="symbol-list"
              value={selectedSymbol}
              onChange={(e) => setSelectedSymbol(e.target.value)}
              onFocus={loadSymbols}
              placeholder="选择币安合约交易对，如 ETHUSDT"
              className="symbol-input"
            />
            <datalist id="symbol-list">
              {filteredSymbols.map((s) => (
                <option key={s} value={s} />
              ))}
            </datalist>
            <select
              value={interval}
              onChange={(e) => setInterval(e.target.value)}
              className="interval-select"
            >
              {INTERVAL_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
          </div>
        </div>
        <div className="form-item">
          <span className="label">3. 原始 OHLC 数据 (JSON)</span>
          <button
            type="button"
            className="fetch-btn"
            onClick={fetchKline}
            disabled={fetching}
          >
            {fetching ? '抓取中...' : '抓取最新行情'}
          </button>
          <textarea
            value={klineJson}
            onChange={(e) => setKlineJson(e.target.value)}
            rows={6}
            placeholder='[{"time": 123, "open": 100, "high": 101, "low": 99, "close": 100}]'
            className="kline-textarea"
          />
        </div>
        <div className="form-item">
          <span className="label">4. 分析指令 (驯化提示词)</span>
          <input
            value={userQuery}
            onChange={(e) => setUserQuery(e.target.value)}
            placeholder="请根据当前的 K 线图形和原始数据，识别趋势并标注买卖点。"
            className="query-input"
          />
        </div>
        <div className="form-item">
          <button
            type="button"
            className="analyze-btn"
            onClick={runAnalyze}
            disabled={analyzing}
          >
            {analyzing ? '分析中...' : '开始 AI 综合分析'}
          </button>
        </div>
      </div>

      <div className="chart-card card-block">
        <h4>K 线策略可视化</h4>
        <div ref={chartRef} className="chart-container" />
      </div>

      <div className="output-card card-block">
        <h4>DeepSeek V3 策略分析报告</h4>
        <div className="output-content">{analysisOutput || '等待分析...'}</div>
      </div>
    </div>
  )
}

export default AiLab
